set(SOURCES
    SOURCE/Granulator.cpp
    SOURCE/Granulator.h
    SOURCE/PITCH/GrainCorrector.cpp
    SOURCE/PITCH/GrainCorrector.h
    SOURCE/PITCH/PitchCorrector.cpp
    SOURCE/PITCH/PitchCorrector.h
    SOURCE/PITCH/PitchDetector.cpp
    SOURCE/PITCH/PitchDetector.h
    SOURCE/PITCH/PitchDetector_backup.cpp
    SOURCE/PITCH/PitchDetector_backup.h
    SOURCE/PITCH/PitchMarkedCircularBuffer.cpp
    SOURCE/PITCH/PitchMarkedCircularBuffer.h
    SOURCE/PluginEditor.cpp
    SOURCE/PluginEditor.h
    SOURCE/PluginProcessor.cpp
    SOURCE/PluginProcessor.h
    SOURCE/Util/Juce_Header.h
    SUBMODULES/RD/SOURCE/AudioFileHelpers.h
    SUBMODULES/RD/SOURCE/AudioFileProcessor.cpp
    SUBMODULES/RD/SOURCE/AudioFileProcessor.h
    SUBMODULES/RD/SOURCE/BufferFiller.h
    SUBMODULES/RD/SOURCE/BufferHelper.cpp
    SUBMODULES/RD/SOURCE/BufferHelper.h
    SUBMODULES/RD/SOURCE/BufferMath.h
    SUBMODULES/RD/SOURCE/BufferWriter.h
    SUBMODULES/RD/SOURCE/CircularBuffer.cpp
    SUBMODULES/RD/SOURCE/CircularBuffer.h
    SUBMODULES/RD/SOURCE/EFFECTS/GainProcessor.cpp
    SUBMODULES/RD/SOURCE/EFFECTS/GainProcessor.h
    SUBMODULES/RD/SOURCE/Interpolator.h
    SUBMODULES/RD/SOURCE/RelativeFilePath.h
    SUBMODULES/RD/SOURCE/Window.cpp
    SUBMODULES/RD/SOURCE/Window.h
)