set(SOURCES
    SOURCE/DSP_TOOLS/BufferFiller.h
    SOURCE/DSP_TOOLS/CircularBuffer.cpp
    SOURCE/DSP_TOOLS/CircularBuffer.h
    SOURCE/DSP_TOOLS/Window.cpp
    SOURCE/DSP_TOOLS/Window.h
    SOURCE/PITCH/PitchCorrector.cpp
    SOURCE/PITCH/PitchCorrector.h
    SOURCE/PITCH/PitchDetector.cpp
    SOURCE/PITCH/PitchDetector.h
    SOURCE/PITCH/PitchMarkedCircularBuffer.cpp
    SOURCE/PITCH/PitchMarkedCircularBuffer.h
    SOURCE/PluginEditor.cpp
    SOURCE/PluginEditor.h
    SOURCE/PluginProcessor.cpp
    SOURCE/PluginProcessor.h
    SOURCE/Util/Juce_Header.h
    SUBMODULES/RD/SOURCE/BufferFiller.h
    SUBMODULES/RD/SOURCE/CircularBuffer.cpp
    SUBMODULES/RD/SOURCE/CircularBuffer.h
    SUBMODULES/RD/SOURCE/Window.cpp
    SUBMODULES/RD/SOURCE/Window.h
)