set(TESTS
    SUBMODULES/RD/TESTS/TEST_UTILS/BufferGenerator.h
    SUBMODULES/RD/TESTS/TEST_UTILS/TestUtils.cpp
    SUBMODULES/RD/TESTS/TEST_UTILS/TestUtils.h
    SUBMODULES/RD/TESTS/test_BufferFiller.cpp
    SUBMODULES/RD/TESTS/test_CircularBuffer.cpp
    SUBMODULES/RD/TESTS/test_Windowing.cpp
    TESTS/test_PluginBasics.cpp
)