set(TESTS
    SUBMODULES/RD/TESTS/TEST_UTILS/BufferGenerator.h
    SUBMODULES/RD/TESTS/TEST_UTILS/TestUtils.cpp
    SUBMODULES/RD/TESTS/TEST_UTILS/TestUtils.h
    SUBMODULES/RD/TESTS/test_AudioFileHelpers.cpp
    SUBMODULES/RD/TESTS/test_AudioFileProcessor.cpp
    SUBMODULES/RD/TESTS/test_BufferFiller.cpp
    SUBMODULES/RD/TESTS/test_BufferHelper.cpp
    SUBMODULES/RD/TESTS/test_BufferMath.cpp
    SUBMODULES/RD/TESTS/test_BufferRange.cpp
    SUBMODULES/RD/TESTS/test_BufferWriter.cpp
    SUBMODULES/RD/TESTS/test_CircularBuffer.cpp
    SUBMODULES/RD/TESTS/test_RelativeFilePath.cpp
    SUBMODULES/RD/TESTS/test_Windowing.cpp
    SUBMODULES/RD/TESTS/tests_Interpolator.cpp
    TESTS/TEST_UTILS/BufferGenerator.h
    TESTS/test_Grain.cpp
    TESTS/test_GrainCorrector.cpp
    TESTS/test_Granulator.cpp
    TESTS/test_PitchDetector.cpp
    TESTS/test_PitchMarkedCircularBuffer.cpp
    TESTS/test_PluginBasics.cpp
    TESTS/test_ProcessAudioFile.cpp
)